/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package py.una.pol.clientetcp.GUI;

import py.una.pol.clientetcp.Menu;

/**
 *
 * @author jlgut
 */
public class guiRoot extends javax.swing.JPanel {

    /**
     * Creates new form guiRoot
     */
    public guiRoot() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        rbDetener = new javax.swing.JRadioButton();
        rbMatar = new javax.swing.JRadioButton();
        rbApagar = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtInforme = new javax.swing.JLabel();

        setName(""); // NOI18N

        jLabel2.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel2.setText("Informe completo:");

        jButton3.setBackground(new java.awt.Color(255, 0, 0));
        jButton3.setText("X");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jLabel3.setText("Que desea hacer root?");

        rbDetener.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        rbDetener.setText("Detener servicio");
        rbDetener.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbDetenerActionPerformed(evt);
            }
        });

        rbMatar.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        rbMatar.setText("Matar proceso server");
        rbMatar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbMatarActionPerformed(evt);
            }
        });

        rbApagar.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        rbApagar.setForeground(new java.awt.Color(204, 0, 0));
        rbApagar.setText("Apagar servidor");
        rbApagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbApagarActionPerformed(evt);
            }
        });

        txtInforme.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        txtInforme.setText("-informe-");
        jScrollPane1.setViewportView(txtInforme);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbMatar)
                            .addComponent(rbDetener)
                            .addComponent(rbApagar)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel3)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 721, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(0, 52, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton3)
                        .addGap(142, 142, 142))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rbDetener)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbMatar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbApagar)))
                .addGap(40, 40, 40)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void rbDetenerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbDetenerActionPerformed
        Menu.accionRoot = "Detener";
        if(this.rbDetener.isSelected()){
            this.rbMatar.setSelected(false);
            this.rbApagar.setSelected(false);
        }
    }//GEN-LAST:event_rbDetenerActionPerformed

    private void rbMatarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbMatarActionPerformed
        Menu.accionRoot = "Matar";
        if(this.rbMatar.isSelected()){
            this.rbDetener.setSelected(false);
            this.rbApagar.setSelected(false);
        }
    }//GEN-LAST:event_rbMatarActionPerformed

    private void rbApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbApagarActionPerformed
        Menu.accionRoot = "Apagar";
        if(this.rbApagar.isSelected()){
            this.rbMatar.setSelected(false);
            this.rbDetener.setSelected(false);
        }
    }//GEN-LAST:event_rbApagarActionPerformed

    public void setInforme(String informe){
        this.txtInforme.setText(informe);
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rbApagar;
    private javax.swing.JRadioButton rbDetener;
    private javax.swing.JRadioButton rbMatar;
    private javax.swing.JLabel txtInforme;
    // End of variables declaration//GEN-END:variables
}
